"""Custom CNN encoder, embedding head, and S2.4 forward-pass validation.

Preprocessed image tensor → raw features → L2-normalized embedding.
No training loop, loss, similarity, ranking, or pretrained backbones.
"""

from .config import (
    ARCHITECTURE_ID,
    ARCHITECTURE_POLICY,
    DEFAULT_ACTIVATION,
    DEFAULT_BLOCK_CHANNELS,
    DEFAULT_CONVS_PER_STAGE,
    DEFAULT_EMBEDDING_DIM,
    DEFAULT_FEATURE_DIM,
    DEFAULT_HEAD_EMBEDDING_DIM,
    DEFAULT_INPUT_CHANNELS,
    DEFAULT_INPUT_HEIGHT,
    DEFAULT_INPUT_WIDTH,
    DEFAULT_KERNEL_SIZE,
    DEFAULT_NORMALIZATION,
    EMBEDDING_HEAD_POLICY,
    SUPPORTED_EMBEDDING_DIMS,
    EmbeddingHeadConfig,
    EncoderConfig,
)
from .embedding_head import EmbeddingHead, EncoderWithEmbeddingHead
from .encoder import (
    CustomCNNEncoder,
    count_parameters,
    estimate_parameter_bytes,
    format_encoder_summary,
    summarize_encoder,
    trace_encoder_shapes,
)
from .errors import (
    EmbeddingHeadConfigError,
    EmbeddingHeadInputError,
    EncoderConfigError,
    EncoderInputError,
    ForwardPassValidationError,
    ModelError,
)
from .forward_pass import (
    ENCODER_FEATURE_DIM,
    EXPECTED_IMAGE_SHAPE,
    L2_ATOL,
    REQUIRED_BATCH_SIZES,
    collect_l2_stats,
    collect_tensor_stats,
    dataset1_available,
    detect_device,
    load_dataset1_image_batch,
    preprocessed_images_from_preprocessor,
    run_forward_pass,
    validate_embeddings,
    validate_encoder_features,
    validate_input_tensor,
)
from .interfaces import Encoder, validate_embedding_head_input, validate_encoder_input

__all__ = [
    "ARCHITECTURE_ID",
    "ARCHITECTURE_POLICY",
    "DEFAULT_ACTIVATION",
    "DEFAULT_BLOCK_CHANNELS",
    "DEFAULT_CONVS_PER_STAGE",
    "DEFAULT_EMBEDDING_DIM",
    "DEFAULT_FEATURE_DIM",
    "DEFAULT_HEAD_EMBEDDING_DIM",
    "DEFAULT_INPUT_CHANNELS",
    "DEFAULT_INPUT_HEIGHT",
    "DEFAULT_INPUT_WIDTH",
    "DEFAULT_KERNEL_SIZE",
    "DEFAULT_NORMALIZATION",
    "EMBEDDING_HEAD_POLICY",
    "SUPPORTED_EMBEDDING_DIMS",
    "CustomCNNEncoder",
    "EmbeddingHead",
    "EmbeddingHeadConfig",
    "EmbeddingHeadConfigError",
    "EmbeddingHeadInputError",
    "Encoder",
    "EncoderConfig",
    "EncoderConfigError",
    "EncoderInputError",
    "EncoderWithEmbeddingHead",
    "ENCODER_FEATURE_DIM",
    "EXPECTED_IMAGE_SHAPE",
    "ForwardPassValidationError",
    "L2_ATOL",
    "ModelError",
    "REQUIRED_BATCH_SIZES",
    "collect_l2_stats",
    "collect_tensor_stats",
    "dataset1_available",
    "detect_device",
    "load_dataset1_image_batch",
    "preprocessed_images_from_preprocessor",
    "run_forward_pass",
    "validate_embeddings",
    "validate_encoder_features",
    "validate_input_tensor",
    "count_parameters",
    "estimate_parameter_bytes",
    "format_encoder_summary",
    "summarize_encoder",
    "trace_encoder_shapes",
    "validate_embedding_head_input",
    "validate_encoder_input",
]
